org.quartz.scheduler.skipUpdateCheck = true
org.quartz.jobStore.class = org.quartz.simpl.RAMJobStore
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 1
org.quartz.plugin.jobInitializer.class = org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin
org.quartz.plugin.jobInitializer.fileNames = quartz-initial-jobstore.xml
org.quartz.plugin.jobInitializer.failOnFileNotFound = false
org.quartz.plugin.shutdownhook.class = org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownhook.cleanShutdown = true
# 900 seconds * 1000 millis / 60 = 15 minutes -- acting like more like a queue
org.quartz.jobStore.misfireThreshold = 900000
#
# You can run multiple schedulers w/ different configurations so one is
# for quick jobs on a tight schedule and one is for processing items more
# like a queue.