import React from 'react'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '@progress/kendo-theme-default/dist/all.css';
import '@progress/kendo-theme-utils/dist/all.css';
import '../globals.css';

import { AppBar, AppBarSection, AppBarSpacer, Drawer, DrawerContent } from "@progress/kendo-react-layout";
import { Button } from '@progress/kendo-react-buttons';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
  
const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
 });

export default function DemoLayout({
	children,
}: {
  children: React.ReactNode
}) {

	return(
		<html lang="en">
			<body className={roboto.className}>
				<AppBar>
					<AppBarSection>
						JOE
					</AppBarSection>
					<AppBarSpacer style={{width: 32}}/>
					<AppBarSection>
						SAM
					</AppBarSection>
				</AppBar>
				<Drawer>
					<DrawerContent>
						<Button name="hi"/>
					</DrawerContent>
				</Drawer>
				{children}
			</body>
	  	</html>
	)
}